{
  try {
    set(future.get());
  }
 catch (  InterruptedException e) {
    cancel(true);
  }
catch (  CancellationException e) {
    cancel(true);
  }
catch (  ExecutionException e) {
    setException(e.getCause());
  }
}
