{
  try {
    invokable.run();
  }
 catch (  Exception e) {
    if (e.getClass().isAssignableFrom(expectedClass)) {
      return;
    }
 else {
      throw new AssertionError("Expected: " + expectedClass.getName() + ", got: "+ e.getClass().getName());
    }
  }
  throw new AssertionError("No exception thrown");
}
