{
  afterCalled=true;
  resultValue=result;
  if (raiseException) {
    throw new UnsupportedOperationException("Test exception");
  }
}
