{
  SmsTracker tracker=(SmsTracker)ar.userObj;
  PendingIntent sentIntent=tracker.mSentIntent;
  if (ar.exception == null) {
    if (false) {
      Log.d(TAG,"SMS send complete. Broadcasting " + "intent: " + sentIntent);
    }
    if (tracker.mDeliveryIntent != null) {
      int messageRef=((SmsResponse)ar.result).messageRef;
      tracker.mMessageRef=messageRef;
      deliveryPendingList.add(tracker);
    }
    if (sentIntent != null) {
      try {
        if (mRemainingMessages > -1) {
          mRemainingMessages--;
        }
        if (mRemainingMessages == 0) {
          Intent sendNext=new Intent();
          sendNext.putExtra(SEND_NEXT_MSG_EXTRA,true);
          sentIntent.send(mContext,Activity.RESULT_OK,sendNext);
        }
 else {
          sentIntent.send(Activity.RESULT_OK);
        }
      }
 catch (      CanceledException ex) {
      }
    }
  }
 else {
    if (false) {
      Log.d(TAG,"SMS send failed");
    }
    int ss=mPhone.getServiceState().getState();
    if (ss != ServiceState.STATE_IN_SERVICE) {
      handleNotInService(ss,tracker);
    }
 else     if ((((CommandException)(ar.exception)).getCommandError() == CommandException.Error.SMS_FAIL_RETRY) && tracker.mRetryCount < MAX_SEND_RETRIES) {
      tracker.mRetryCount++;
      Message retryMsg=obtainMessage(EVENT_SEND_RETRY,tracker);
      sendMessageDelayed(retryMsg,SEND_RETRY_DELAY);
    }
 else     if (tracker.mSentIntent != null) {
      int error=RESULT_ERROR_GENERIC_FAILURE;
      if (((CommandException)(ar.exception)).getCommandError() == CommandException.Error.FDN_CHECK_FAILURE) {
        error=RESULT_ERROR_FDN_CHECK_FAILURE;
      }
      try {
        Intent fillIn=new Intent();
        if (ar.result != null) {
          fillIn.putExtra("errorCode",((SmsResponse)ar.result).errorCode);
        }
        if (mRemainingMessages > -1) {
          mRemainingMessages--;
        }
        if (mRemainingMessages == 0) {
          fillIn.putExtra(SEND_NEXT_MSG_EXTRA,true);
        }
        tracker.mSentIntent.send(mContext,error,fillIn);
      }
 catch (      CanceledException ex) {
      }
    }
  }
}
