{
  prepareLooper();
  if (mJustCount) {
    mResults.putString(Instrumentation.REPORT_KEY_IDENTIFIER,REPORT_VALUE_ID);
    mResults.putInt(REPORT_KEY_NUM_TOTAL,mTestCount);
    finish(Activity.RESULT_OK,mResults);
  }
 else {
    if (mDebug) {
      Debug.waitForDebugger();
    }
    ByteArrayOutputStream byteArrayOutputStream=new ByteArrayOutputStream();
    PrintStream writer=new PrintStream(byteArrayOutputStream);
    try {
      StringResultPrinter resultPrinter=new StringResultPrinter(writer);
      mTestRunner.addTestListener(resultPrinter);
      long startTime=System.currentTimeMillis();
      mTestRunner.runTest();
      long runTime=System.currentTimeMillis() - startTime;
      resultPrinter.printResult(mTestRunner.getTestResult(),runTime);
    }
 catch (    Throwable t) {
      writer.println(String.format("Test run aborted due to unexpected exception: %s",t.getMessage()));
      t.printStackTrace(writer);
    }
 finally {
      mResults.putString(Instrumentation.REPORT_KEY_STREAMRESULT,String.format("\nTest results for %s=%s",mTestRunner.getTestClassName(),byteArrayOutputStream.toString()));
      if (mCoverage) {
        generateCoverageReport();
      }
      writer.close();
      finish(Activity.RESULT_OK,mResults);
    }
  }
}
